### ISSUE TITLE
Different size between defocused image and defocus map in RTF dataset

### ISSUE THREAD

**Issue by binorchen** [codeslake/SYNDOF#3]
I found a problem in the shared RTF dataset.
The size of the defocused image is 360 x 360, while the size of ground truth defocus map is 340 x 360.
I noticed you gave the MSE and MAE of defocus map evaluation.
May I know you just cut 20 pixels off or resize it?

**Comment by codeslake** [comment]
Hi, Chen!
I actually have asked the same exact question to the author of RTF dataset.
If I quote what he said,
"
To be more precised, the right part of the images have been cropped in width (i.e. the defocus blur map estimations as well as the deblurred images are cropped). You can visually see that by opening side to side an image in "Noisy_Blurred_Images" (360x360) and the same in "Deblurred_Results" (360x340).
"
Thanks!

**Comment by binorchen** [comment]
Thanks a lot! 
It's very helpful!
Regards
