### ISSUE TITLE
Code is not reading the files

### ISSUE THREAD

**Issue by Reza-Asiyabi** [codeslake/SYNDOF#4]
While compiling the code, it gives the following error:

Reference to non-existent field 'folder'.

Error in generate_blur_by_depth>dir2 (line 136)
        file_path = listing(k).folder;

Error in generate_blur_by_depth (line 14)
    kernel_file_paths = dir2([offset, filesep, 'kernel', filesep, '*']);

And if we delete the kernel images from the kernel folder, it runs but the variables "image_file_paths" and "depth_file_paths" are empty and as a result, the code stuck in the while loop!

**Comment by codeslake** [comment]
Hi, @Reza-MohammadiAsiyabi.

I've just run my code without a problem (I am using MATLAB R2021a).

Did you give proper `offset_in` for the function `generate_blur_by_depth(max_coc, offset_in, offset_out, is_random_gen, is_gpu, gpunum)`? 
I also stuck in the while loop if I intentionally give the wrong offset for the `offset_in`.

**Comment by Reza-Asiyabi** [comment]
Thank you @codeslake for checking!

I am giving the command (below), as mentioned in the Readme file:
`generate_blur_by_depth(29, 'data', 'out', false, true, 1)`
So the `offset_in` is 'data'

But I am using MATLAB R2016a! Can it be the problem?

**Comment by saqibnaziir** [comment]
I face the same problem!!!!

Reference to non-existent field 'folder'.

Error in generate_blur_by_depth>dir2 (line 136)
file_path = listing(k).folder;

Error in generate_blur_by_depth (line 14)
kernel_file_paths = dir2([offset, filesep, 'kernel', filesep, '*']);

**Comment by codeslake** [comment]
Hi, @Reza-MohammadiAsiyabi, @saqibnaziir.

I believe it is Matlab's version problem.
For 2016a, the struct returned by `dir()` function does not have `folder` attribute, which should contain the relative path of a file.

I've just committed a new code with function `dir3()`. It took me some time to check the document of 2016a to make sure of the compatibility.
Change the `dir2` callings to `dir3` for lines [10](https://github.com/codeslake/SYNDOF/blob/master/generate_blur_by_depth.m#L10), [11](https://github.com/codeslake/SYNDOF/blob/master/generate_blur_by_depth.m#L11), [12](https://github.com/codeslake/SYNDOF/blob/master/generate_blur_by_depth.m#L12) and run the code again.
Please let me know if you guys encounter further problems.

**Comment by saqibnaziir** [comment]
Thank you @codeslake!!
I just tried to compile the code on Matlab2021a but i get this error. 

=================================================================
[blurring start..]
'datasample' requires Statistics and Machine Learning Toolbox.

Error in blur_by_depth>get_cocs (line 159)
    f = datasample([50, 70, 85], 1, 'Weights', [0.1, 0.4, 0.4]);

Error in blur_by_depth (line 14)
        [cocs, depth_map, camera_params] = get_cocs(depth_map_origin, size(image, 2), max_coc);

Error in generate_blur_by_depth (line 60)
                blur_by_depth(image_file_path, depth_file_path, depth_scale, kernel_type, max_coc, is_gpu);

**Comment by codeslake** [comment]
Hey, @saqibnaziir. 
You need to install **Statistics and Machine Learning Toolbox**.
For Matlab GUI, if you click on the text, the installation process will begin.

You will have to google the installation process if you are using terminal-based Matlab.

**Comment by saqibnaziir** [comment]
Thank you very much @codeslake for your fast replies. I don't have this toolbox so i will install it first.

**Comment by codeslake** [comment]
@saqibnaziir, @Reza-MohammadiAsiyabi, reopen the issue if you guys get any more problems!
Closing the issue.
