### ISSUE TITLE
Questions about the alpha-blend.

### ISSUE THREAD

**Issue by ByChelsea** [codeslake/SYNDOF#5]
Hi,
  Thanks for your codes. 

  As for the alpha-blend part, I don't really understand these two lines of code in the **blur_by_depth.m** file:

`merged_image = (1 - merge_mask) .* merged_image + foreground;
merged_mask = (1 - merge_mask) .* merged_mask + merge_mask;`

  I think the transparency of the edge pixels is already taken into account when the sub-image is blurred, because all pixels beyond the sub-image are 0, which means edge pixels  affected by these pixels are already semitransparent. However, the alpha-blend operation seems to consider transparency twice...

  This puzzled me for a long time...

**Comment by codeslake** [comment]
Hi,
I would like to note that the code is not re-considering semi-transparent regions of `merged_image` and `foreground` images.

As you can see in the line of the code that you brought out, there is no alpha value for the `foreground` image, as its border is already semi-transparent.
However, the border of `merged_image` is not semi-transparent, which is handled in [here](https://github.com/codeslake/SYNDOF/blob/master/blur_by_depth.m#L322) (if I remember correctly.).

**Comment by ByChelsea** [comment]
Why the border of `merged_image` is not semi-transparent? The `merged_image` is the sum of `foreground`(even if there's no alpha value), thus, I think it should still be semi-transparent...

**Comment by codeslake** [comment]
For example, the semi-transparent values become 1 (non-transparent) with the following line.
`merged_mask = merged_mask ./ merged_mask_temp;`

**Comment by ByChelsea** [comment]
This line of code only executes if `i > coc_zero_idx`, and the border of `merged_image` will be semi-transparent when `i <= coc_zero_idx`...

**Comment by codeslake** [comment]
Thanks for pointing it out.
I've closely checked the code again.

First of all, I believe that [these lines](https://github.com/codeslake/SYNDOF/blob/master/blur_by_depth.m#L320-L323) should be removed. I think there was a mistake when I reorganized this code to make it public. I will check the original code as soon as possible.

If I go back to your questions,
it is ambiguous to blend two semi-transparent regions, as the kernel used for each region is independent.
As they are independent, we cannot naively blend them. The blended pixel value may exceed 1 (255) or still be semi-transparent.

What we do in this code is, to use `merge_mask` as blending weights when mixing two semi-transparent regions, and use `merged_mask` to make pixels to be non-transparent ([this line](https://github.com/codeslake/SYNDOF/blob/master/blur_by_depth.m#L78), or you can consider this as a normalization).

**Comment by ByChelsea** [comment]
Thanks for your kind reply and I'm looking forward to the modified code.

I couldn't agree more that the blended pixel value may exceed 1 (255) or still be semi-transparent. But why does it have to be equal to 1? 

Not being equal to 1 is probably a natural thing that fits into the thin lens model, because there's no `normalization` in the thin lens model. But that's just my opinion. What's yours?

**Comment by codeslake** [comment]
>  couldn't agree more that the blended pixel value may exceed 1 (255) or still be semi-transparent. But why does it have to be equal to 1?

As we keep stacking (merging) blurred images, pixels have a chance to have values over 1.
Moreover, depending on sigma values between staked images, there is also a chance to have a transparent value.
Imagine two original masks filled with 1s but blurred to have values 0.1 and 0.2. Naively adding them will have 0.3 (transparent).

>Not being equal to 1 is probably a natural thing that fits into the thin lens model, because there's no normalization in the thin lens model. But that's just my opinion. What's yours?

We use the thins lens model to compute the size of CoCs, not the shape of CoC (bokeh), which can be differed depend on what aperture shape you choose.
We choose Gaussian, which creates a semi-transparent region around the masked edges, for which we need a `normalization`.
If we have chosen isotropic kernels uniformly filled with 1s, naive alpha blending with `alpha=0.5` would have been ok.

**Comment by ByChelsea** [comment]
Actually, I mean I agree that "the blended pixel value may exceed 1 (255) or still be semi-transparent" and I know how this phenomenon comes about. 

But maybe the `normalization` is not necessary and it's okay to leave the pixel value exceed 1 or semi-transparent? I think this is different from the case where the sum of the weights of the blur kernel must be equal to 1...

**Comment by codeslake** [comment]
> But maybe the normalization is not necessary and it's okay to leave the pixel value exceed 1 or semi-transparent? I think this is different from the case where the sum of the weights of the blur kernel must be equal to 1...

If we don't do the normalization, the defocused image will contain odd seams around masked edges.

Think of a mask value as 'exposure', where 1 means the appropriate exposure needed for a pixel to be present as it is in the all-in-focus image. Then, normalization can be thought of as making pixels in merged transparent regions to have the appropriate exposure.

**Comment by ByChelsea** [comment]
Thanks a lot! This is very helpful!
