### ISSUE TITLE
When to use the normalized defocus map

### ISSUE THREAD

**Issue by ryanxingql** [codeslake/SYNDOF#6]
Hi Lee, thanks for your great job!
I am wondering that when you use the normalized defocus map?
It seems that you use the unnormalized defocus map for training, and only generate the normalized map in test.
If the normalized map is used only for visualization?
Thank you.

**Comment by codeslake** [comment]
Hi, Qunliang.

Yes, it is for visualization!

**Comment by ryanxingql** [comment]
Thanks for your timely response!
Great job! ^ ^
