### ISSUE TITLE
Middleburry might already have defocus blur.

### ISSUE THREAD

**Issue by ByChelsea** [codeslake/SYNDOF#7]
Hi,
Thanks for your great work. I have a question: what if the images in Middleburry already have defocus blur? Because the images are taken by the actual camera, defocus blur might be inevitable...

I tried to rule out the out-of-focus images using the `formula 1`  in your paper DMENet, but there's no aperture information in Middleburry...

**Comment by codeslake** [comment]
Hi, @ByChelsea.
If I remember correctly, it was hard for me to find defocus blur in the Middlebury dataset (I believe it was one of the reasons that the dataset is chosen).

**Comment by ByChelsea** [comment]
Hi,
Thanks for your reply! But it doesn't seem to make sense to determine if there is an defocus blur just by feeling it.  I think maybe we need to calculate it as I mentioned above.

**Comment by codeslake** [comment]
I've just looked through the Middlebury dataset, I believe the scene captured is in the focused range.
But yes, I agree. It would be better if we somehow ignored defocused patches for creating the dataset.

**Comment by ByChelsea** [comment]
Thanks a lot for your kind reply!
